#define GCC42 0
#define CLANG3 1
#define COMPILER CLANG3

#if COMPILER == GCC42
    /*
     XCode 4.4 build settings:
     	Build options
			Compiler for C/C++/Objective-C: LLVM GCC 4.2
     */
    #define ALIAS_TEMPLATES 1
    #define ALTERNATIVE_FUNCTION_SYNTAX 0
    #define EXPLICIT_FINAL 0
    #define EXPLICIT_OVERRIDE 0
    #define EXPLICITLY_DEFAULTED_SPECIAL_MEMBER_FUNCTIONS 0
    #define EXPLICITLY_DELETED_MEMBER_FUNCTIONS 0
    #define GENERALIZED_CONSTANT 0
    #define HASH_TABLES 0
    #define INITIALIZER_LISTS 0
    #define LAMBDA_FUNCTIONS 0
    #define LONG_LONG_INT 1
    #define NEW_STRING_LITERALS 0
    #define NULLPTR 0
    #define OBJECT_CONSTRUCTION_CONSTRUCTORS_CALLING_CONSTRUCTORS 0
    #define OBJECT_CONSTRUCTION_IMPROVEMENT_USING_BASE_CONSTRUCTOR 0
    #define POLYMORPHIC_WRAPPERS_FOR_FUNCTION_OBJECTS 0
    #define RANDOM_NUMBERS 0
    #define RANGE_BASED_FOR_LOOP 0
    #define REGEX 0
    #define RIGHT_ANGLE_BRACKETS 0
    #define SHARED_PTR 0
    #define SIZEOF_ON_MEMBER_OBJECTS 0
    #define STATIC_ASSERT 0
    #define STRONGLY_TYPED_ENUM 0
    #define TEMPLATES_WITH_VARIABLE_NUMBER_OF_VALUES 0
    #define TEMPLATES_WITH_VARIABLE_NUMBER_OF_VARIABLES 0
    #define TUPLE 0
    #define TYPE_INFERENCE_AUTO 0
    #define TYPE_INFERENCE_DECLTYPE 0
    #define TYPE_TRAITS_METAPROGRAMMING 0
    #define UNIFORM_INITIALIZATION 0
    #define UNRESTRICTED_UNIONS 0
    #define USER_DEFINED_LITERALS 0
    #define USING_SYNTAX_INSTEAD_OF_TYPEDEFS 0
    #define WRAPPER_REFERENCE 0
#endif

#if COMPILER == CLANG3
	/*
	XCode 4.4 build settings:
	 	Build options
			Compiler for C/C++/Objective-C: Apple LLVM compiler 4.0
		Apple LLVM compiler 4.0 - Language
			C++ Language Dialect: C++11 [-std=c++11]
			C++ Standard Library: libc++ (LLVM C++ standard library with C++11 support)
	*/

    #define ALIAS_TEMPLATES 1
    #define ALTERNATIVE_FUNCTION_SYNTAX 1
    #define EXPLICIT_FINAL 1
    #define EXPLICIT_OVERRIDE 1
    #define EXPLICITLY_DEFAULTED_SPECIAL_MEMBER_FUNCTIONS 1
    #define EXPLICITLY_DELETED_MEMBER_FUNCTIONS 1
    #define GENERALIZED_CONSTANT 0 // 3.1+
    #define HASH_TABLES 0
    #define INITIALIZER_LISTS 0 // 3.1+
    #define LAMBDA_FUNCTIONS 0 // 3.1+
    #define LONG_LONG_INT 1
    #define NEW_STRING_LITERALS 1
    #define NULLPTR 1
    #define OBJECT_CONSTRUCTION_CONSTRUCTORS_CALLING_CONSTRUCTORS 1
    #define OBJECT_CONSTRUCTION_IMPROVEMENT_USING_BASE_CONSTRUCTOR 0
    #define POLYMORPHIC_WRAPPERS_FOR_FUNCTION_OBJECTS 0
    #define RANDOM_NUMBERS 1
    #define RANGE_BASED_FOR_LOOP 1
    #define REGEX 1
    #define RIGHT_ANGLE_BRACKETS 1
    #define SHARED_PTR 1
    #define SIZEOF_ON_MEMBER_OBJECTS 1
    #define STATIC_ASSERT 1
    #define STRONGLY_TYPED_ENUM 1
    #define TEMPLATES_WITH_VARIABLE_NUMBER_OF_VALUES 1
    #define TEMPLATES_WITH_VARIABLE_NUMBER_OF_VARIABLES 1
    #define TUPLE 1
    #define TYPE_INFERENCE_AUTO 1
    #define TYPE_INFERENCE_DECLTYPE 1
    #define TYPE_TRAITS_METAPROGRAMMING 1
    #define UNIFORM_INITIALIZATION 1
    #define UNRESTRICTED_UNIONS 1
    #define USER_DEFINED_LITERALS 0 // 3.1+
    #define USING_SYNTAX_INSTEAD_OF_TYPEDEFS 1
    #define WRAPPER_REFERENCE 1
#endif